<?php

namespace App\Shared\Enums;

enum RulesEnum: string
{
    case USERS_VIEW = 'USERS_VIEW';

    case ADMIN_USERS_ADMIN_MASTER_VIEW   = 'ADMIN_USERS_ADMIN_MASTER_VIEW';
    case ADMIN_USERS_ADMIN_MASTER_INSERT = 'ADMIN_USERS_ADMIN_MASTER_INSERT';
    case ADMIN_USERS_ADMIN_MASTER_UPDATE = 'ADMIN_USERS_ADMIN_MASTER_UPDATE';

    case ADMIN_USERS_ADMIN_CHURCH_VIEW   = 'ADMIN_USERS_ADMIN_CHURCH_VIEW';
    case ADMIN_USERS_ADMIN_CHURCH_INSERT = 'ADMIN_USERS_ADMIN_CHURCH_INSERT';
    case ADMIN_USERS_ADMIN_CHURCH_UPDATE = 'ADMIN_USERS_ADMIN_CHURCH_UPDATE';
    case ADMIN_USERS_ADMIN_CHURCH_DELETE = 'ADMIN_USERS_ADMIN_CHURCH_DELETE';

    case ADMIN_USERS_ADMIN_MODULE_VIEW   = 'ADMIN_USERS_ADMIN_MODULE_VIEW';
    case ADMIN_USERS_ADMIN_MODULE_INSERT = 'ADMIN_USERS_ADMIN_MODULE_INSERT';
    case ADMIN_USERS_ADMIN_MODULE_UPDATE = 'ADMIN_USERS_ADMIN_MODULE_UPDATE';
    case ADMIN_USERS_ADMIN_MODULE_DELETE = 'ADMIN_USERS_ADMIN_MODULE_DELETE';

    case ADMIN_USERS_ASSISTANT_VIEW   = 'ADMIN_USERS_ASSISTANT_VIEW';
    case ADMIN_USERS_ASSISTANT_INSERT = 'ADMIN_USERS_ASSISTANT_INSERT';
    case ADMIN_USERS_ASSISTANT_UPDATE = 'ADMIN_USERS_ASSISTANT_UPDATE';
    case ADMIN_USERS_ASSISTANT_DELETE = 'ADMIN_USERS_ASSISTANT_DELETE';

    case ADMIN_USERS_MEMBER_VIEW   = 'ADMIN_USERS_MEMBER_VIEW';
    case ADMIN_USERS_MEMBER_INSERT = 'ADMIN_USERS_MEMBER_INSERT';
    case ADMIN_USERS_MEMBER_UPDATE = 'ADMIN_USERS_MEMBER_UPDATE';
    case ADMIN_USERS_MEMBER_DELETE = 'ADMIN_USERS_MEMBER_DELETE';

    case PROFILES_ADMIN_MASTER_VIEW = 'PROFILES_ADMIN_MASTER_VIEW';
    case PROFILES_ADMIN_CHURCH_VIEW = 'PROFILES_ADMIN_CHURCH_VIEW';
    case PROFILES_ADMIN_MODULE_VIEW = 'PROFILES_ADMIN_MODULE_VIEW';
    case PROFILES_ASSISTANT_VIEW = 'PROFILES_ASSISTANT_VIEW';
    case PROFILES_MEMBER_VIEW = 'PROFILES_MEMBER_VIEW';

    case COUNT_USERS_ADMIN_MASTER_VIEW = 'COUNT_USERS_ADMIN_MASTER_VIEW';
    case COUNT_USERS_ADMIN_CHURCH_VIEW = 'COUNT_USERS_ADMIN_CHURCH_VIEW';
    case COUNT_USERS_ADMIN_MODULE_VIEW = 'COUNT_USERS_ADMIN_MODULE_VIEW';
    case COUNT_USERS_ASSISTANT_VIEW = 'COUNT_USERS_ASSISTANT_VIEW';

    case CITIES_VIEW = 'CITIES_VIEW';
    case STATES_VIEW = 'STATES_VIEW';
    case SYSTEM_VIEW = 'SYSTEM_VIEW';
    case SYSTEM_UPDATE = 'SYSTEM_UPDATE';
}
