<?php

namespace App\Shared\Enums;

enum RulesEnum: string
{
    case USERS_VIEW = 'USERS_VIEW';

    case ADMIN_USERS_ADMIN_MASTER_VIEW = 'ADMIN_USERS_ADMIN_MASTER_VIEW';
    case ADMIN_USERS_ADMIN_MASTER_INSERT = 'ADMIN_USERS_ADMIN_MASTER_INSERT';
    case ADMIN_USERS_ADMIN_MASTER_UPDATE = 'ADMIN_USERS_ADMIN_MASTER_UPDATE';

    case ADMIN_USERS_EMPLOYEE_VIEW = 'ADMIN_USERS_EMPLOYEE_VIEW';
    case ADMIN_USERS_EMPLOYEE_INSERT = 'ADMIN_USERS_EMPLOYEE_INSERT';
    case ADMIN_USERS_EMPLOYEE_UPDATE = 'ADMIN_USERS_EMPLOYEE_UPDATE';

    case PROFILES_ADMIN_MASTER_VIEW = 'PROFILES_ADMIN_MASTER_VIEW';
    case PROFILES_EMPLOYEE_VIEW = 'PROFILES_EMPLOYEE_VIEW';

    case THEMES_VIEW = 'THEMES_VIEW';
    case THEMES_INSERT = 'THEMES_INSERT';
    case THEMES_UPDATE = 'THEMES_UPDATE';
    case THEMES_DELETE = 'THEMES_DELETE';

    case CATEGORIES_VIEW = 'CATEGORIES_VIEW';
    case CATEGORIES_INSERT = 'CATEGORIES_INSERT';
    case CATEGORIES_UPDATE = 'CATEGORIES_UPDATE';
    case CATEGORIES_DELETE = 'CATEGORIES_DELETE';

    case CUSTOMERS_VIEW = 'CUSTOMERS_VIEW';
    case CUSTOMERS_INSERT = 'CUSTOMERS_INSERT';
    case CUSTOMERS_UPDATE = 'CUSTOMERS_UPDATE';
    case CUSTOMERS_DELETE = 'CUSTOMERS_DELETE';

    case EVENTS_VIEW = 'EVENTS_VIEW';
    case EVENTS_INSERT = 'EVENTS_INSERT';
    case EVENTS_UPDATE = 'EVENTS_UPDATE';
    case EVENTS_DELETE = 'EVENTS_DELETE';

    case PRODUCTS_VIEW = 'PRODUCTS_VIEW';
    case PRODUCTS_INSERT = 'PRODUCTS_INSERT';
    case PRODUCTS_UPDATE = 'PRODUCTS_UPDATE';
    case PRODUCTS_DELETE = 'PRODUCTS_DELETE';
    case PRODUCTS_UPLOAD_FILE = 'PRODUCTS_UPLOAD_FILE';

    case CITIES_VIEW = 'CITIES_VIEW';
    case STATES_VIEW = 'STATES_VIEW';
    case SYSTEM_VIEW = 'SYSTEM_VIEW';
    case SYSTEM_UPDATE = 'SYSTEM_UPDATE';
}
